---
require:
  - rubocop-faker
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  # Do not lint generated files
  Exclude:
    - bin/*
    - spec/dummy/bin/*
    - spec/dummy/db/schema.rb
    - coverage/**/*
  TargetRubyVersion: 3.1.2
  NewCops: enable

RSpec:
  Language:
    ExampleGroups:
      Regular:
        - on_patch
        - on_get
        - on_put
        - on_post
        - on_delete
    Examples:
      Regular:
        - for_code
    Expectations:
      - test_response_of

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 16.5
  Exclude:
    # Migrations
    - db/migrate/*.rb
    - spec/dummy/db/migrate/*.rb

Metrics/BlockLength:
  Exclude:
    # Migrations
    - db/migrate/*.rb
    - spec/dummy/db/migrate/*.rb
    # Routes
    - config/routes.rb
    - spec/dummy/config/routes.rb
    # Tasks
    - lib/tasks/*.rake
    - spec/dummy/lib/tasks/*.rake
    # Factories
    - spec/factories/*.rb
    - spec/dummy/spec/factories/*.rb
    # Other
    - spec/**/*_spec.rb
    - spec/support/shared_examples/**/*.rb

Metrics/ClassLength:
  Exclude:
    - db/migrate/*.rb
    - spec/dummy/db/migrate/*.rb

Metrics/MethodLength:
  Max: 12
  Exclude:
    - db/migrate/*.rb
    - spec/dummy/db/migrate/*.rb

Metrics/ModuleLength:
  Exclude:
    - spec/**/*_spec.rb

Rails/DynamicFindBy:
  AllowedMethods:
    # In Actor model
    - find_by_account
    - find_by_federation_url

Rails/FilePath:
  EnforcedStyle: arguments

Rails/I18nLocaleTexts:
  Exclude:
    - spec/dummy/**/*

RSpec/DescribeClass:
  Exclude:
    # Tasks
    - spec/tasks/*_spec.rb
    - spec/dummy/spec/tasks/*_spec.rb

RSpec/ExampleLength:
  Exclude:
    # Migrations
    - spec/migrations/*_spec.rb
    - spec/dummy/spec/migrations/*_spec.rb
    # Views are lengthy by design
    - spec/views/**/*_spec.rb
    - spec/dummy/spec/views/**/*_spec.rb

RSpec/ExpectActual:
  Exclude:
    # Routing specs
    - spec/routing/**/*_spec.rb
    - spec/dummy/spec/routing/**/*_spec.rb

RSpec/FactoryBot/ConsistentParenthesesStyle:
  EnforcedStyle: omit_parentheses

# I prefer to type the whole calls instead of having the methods included in the
# tests
RSpec/FactoryBot/SyntaxMethods:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    # Migrations
    - spec/migrations/*_spec.rb
    - spec/dummy/spec/migrations/*_spec.rb
    # Views spec have multiple expectations by design
    - spec/dummy/spec/views/**/*_spec.rb

RSpec/MultipleMemoizedHelpers:
  Exclude:
    # Migrations
    - spec/migrations/*_spec.rb
    - spec/dummy/spec/migrations/*_spec.rb

RSpec/NestedGroups:
  Max: 4

RSpec/Rails/InferredSpecType:
  Enabled: false

RSpec/RepeatedDescription:
  Exclude:
    # Policies
    - spec/policies/**/*
    - spec/dummy/spec/policies/**/*

RSpec/RepeatedExample:
  Exclude:
    # Policies
    - spec/policies/**/*
    - spec/dummy/spec/policies/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
