---
defaults: &defaults
  app_name: The Dummy App
  app_version: 0.1.0
  force_ssl: false
  site_host: http://localhost
  site_port: 3000
  enable_discovery: true
  app_layout: 'layouts/application'
  user_class: '::User'
  server_routes_path: federation
  client_routes_path: app
  user_profile_url_method: ~
  user_name_field: ~
  user_username_field: id

development:
  <<: *defaults

test:
  <<: *defaults
  site_port: null

production:
  <<: *defaults
  force_ssl: true
  site_port: 443
