---
defaults: &defaults
  force_ssl: false
  site_host: http://localhost
  site_port: 3000
  user_class: '::User'
  routes_path: federation
  user_profile_url_method: ~

development:
  <<: *defaults

test:
  <<: *defaults
  site_port: null

production:
  <<: *defaults
  force_ssl: true
  site_port: 443
