require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/federation/activities', type: :request do
  describe 'GET /outbox' do
    it 'renders a successful response' do
      note = FactoryBot.create :note
      get federation_actor_outbox_url(note.actor, format: :json)
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      FactoryBot.create :note
      activity = Activity.last
      get federation_actor_activity_url(activity.actor_id, activity.id, format: :json)
      expect(response).to be_successful
    end
  end
end
